# Generated by Django 6.0 on 2025-12-09 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0002_pvtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='aadhar_number',
            field=models.CharField(blank=True, help_text='Enter 12 digit Aadhaar number', max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhaar number must be exactly 12 digits.', regex='^\\d{12}$')]),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
