# Generated by Django 6.0 on 2025-12-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0003_member_aadhar_number_member_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvtransaction',
            name='note',
        ),
    ]
