# Generated by Django 6.0 on 2025-12-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0004_remove_pvtransaction_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='aadhar_number',
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
